# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jmZiJ-R5Yt4Ahdada8hOAaVDO9eUuK_6
"""

import numpy as np 
import pandas as pd

df=pd.read_excel("/content/test.xlsx")

df.head()

df.info()

df.describe()

df.shape

df.columns

df.isnull().sum()

# Get the numerical columns
numerical_cols = df.select_dtypes(include=['float64', 'int64']).columns.tolist()

# Get the categorical columns
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()

print('Numerical columns:', numerical_cols)
print('Categorical columns:', categorical_cols)

# create a dictionary to store the mapping of labels to numerical values
label_map = {}

# iterate over the categorical columns
for col in categorical_cols:
    # get the unique values of the column
    unique_vals = df[col].unique()
    
    # create a dictionary to store the mapping of each unique value to a numerical value
    col_map = {}
    
    # assign a numerical value to each unique value
    for i, val in enumerate(unique_vals):
        col_map[val] = i
        
    # store the column mapping in the label_map dictionary
    label_map[col] = col_map
    
    # replace the categorical values in the column with the numerical values
    df[col] = df[col].map(col_map)

df.head()

print(label_map)

# Save the preprocessed data to an Excel file
df.to_excel('test1.xlsx', index=False)

